# Generated by Django 5.0.6 on 2024-10-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_project_id_ratings_project_id_rating_is_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRatings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('rater_id', models.IntegerField()),
                ('rated_id', models.IntegerField()),
                ('score_cooperation', models.IntegerField()),
                ('score_conceptual', models.IntegerField()),
                ('score_practical', models.IntegerField()),
                ('score_workethic', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('team_id', 'rater_id', 'rated_id')},
            },
        ),
    ]
