# Generated by Django 5.0.6 on 2024-11-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_projects_open_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
