# Generated by Django 5.0.6 on 2024-11-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('instructor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects_to_Student_Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamRatings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('rater_id', models.IntegerField()),
                ('rated_id', models.IntegerField()),
                ('score_cooperation', models.IntegerField(max_length=1)),
                ('score_conceptual', models.IntegerField(max_length=1)),
                ('score_practical', models.IntegerField(max_length=1)),
                ('score_workethic', models.IntegerField(max_length=1)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('team_id', 'rater_id', 'rated_id')},
            },
        ),
    ]
