# Generated by Django 5.1.1 on 2024-09-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('open', models.BooleanField(default=False)),
                ('instructor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('rating', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('student_creator_id', models.IntegerField()),
                ('student_rater_id', models.IntegerField()),
                ('score_cooperation', models.CharField(max_length=1)),
                ('score_conceptual', models.CharField(max_length=1)),
                ('score_practical', models.CharField(max_length=1)),
                ('score_workethic', models.CharField(max_length=1)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
