# Generated by Django 5.0.6 on 2024-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_myprojects_people_project_ratings_alter_myuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people_project',
            old_name='rating',
            new_name='rating_complete',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='student_creator_id',
            new_name='student_being_rated_id',
        ),
        migrations.RemoveField(
            model_name='myprojects',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
