# Generated by Django 5.0.6 on 2024-09-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_rating_people_project_rating_complete_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProjects',
            new_name='Projects',
        ),
        migrations.RenameModel(
            old_name='People_Project',
            new_name='Projects_to_Student_Relationships',
        ),
    ]
