# Generated by Django 5.0.6 on 2024-10-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_projects_to_student_relationships_rating_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='project_id',
            new_name='project_id_rating_is_for',
        ),
    ]
