# Generated by Django 5.0.6 on 2024-11-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_teamratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='open',
        ),
        migrations.AlterField(
            model_name='teamratings',
            name='score_conceptual',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='teamratings',
            name='score_cooperation',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='teamratings',
            name='score_practical',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='teamratings',
            name='score_workethic',
            field=models.IntegerField(max_length=1),
        ),
    ]
