name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9,'3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # No need to set up DATABASE_URL for SQLite, as Django defaults to SQLite

      - name: Run Migrations and Tests
        run: |
          cd SOEN341_Project
          python manage.py migrate
          python manage.py test




