name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Python versions to test

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run migrations and tests
      - name: Run Migrations and Tests
        env:
          DJANGO_SETTINGS_MODULE: "mainApp.settings"  # Ensure this matches your Django settings file
        run: |
          python manage.py migrate --noinput
          python manage.py test -v 2  # Verbose output for debugging






